services:
  microphone: # installs like 10gb of libraries and models, do at your own risk
    tty: true
    build: ../backend
    volumes:
      - ./backend:/backend
    container_name: PZSP06_microphone
    ports:
      - "8081:8081"
    expose:
      - 8081
    environment:
      - PULSE_SERVER=${PULSE_SERVER}
    volumes:
      - /mnt/wslg/:/mnt/wslg/
    stdin_open: true
    command: tail -f /dev/null  # keeps the container running